[2022-09-25T14:17:44.372+0000] {taskinstance.py:1159} INFO - Dependencies not met for <TaskInstance: ELT_dag.create_table manual__2022-09-25T14:15:45.328532+00:00 [failed]>, dependency 'Task Instance State' FAILED: Task is in the 'failed' state.
[2022-09-25T14:17:44.519+0000] {local_task_job.py:103} INFO - Task is not able to be run
